name: wecareapp1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  provider: ^6.1.5
  flutter_local_notifications: ^19.4.0
  # Open source mapping
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # Environment configuration
  flutter_dotenv: ^5.1.0
  # HTTP requests for map tiles
  http: ^1.2.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
